/**
 * The full challenge library.
 *
 * Grouped by theme so the seeder can interleave them, which keeps a user from
 * getting thirty kindness tasks in a row. Every entry is one small thing a
 * person can finish in a single day.
 *
 * House rules for adding more:
 *   - Start with a verb. It is an instruction, not a suggestion.
 *   - Keep it under 95 characters. Longer text overflows the challenge card.
 *   - One action per challenge. If it needs an "and", it is probably two.
 *   - No em dashes anywhere.
 *   - It has to be doable today, for free, by someone with an ordinary day.
 *
 * Run `node scripts/check-challenges.mjs` after editing to validate.
 */

export const OUTWARD_STRANGERS = [
  "Compliment three strangers today.",
  "Hold the door for everyone behind you.",
  "Let someone go ahead of you in line.",
  "Learn the name of someone you see often but never asked.",
  "Thank someone in a service job by name.",
  "Leave a kind note where a stranger will find it.",
  "Give up your seat to someone who needs it more.",
  "Pay for the person behind you if you can afford it.",
  "Smile at every person you pass for one whole block.",
  "Help someone carry something heavy.",
  "Give a real answer when someone asks how you are.",
  "Leave a bigger tip than usual and say thank you out loud.",
  "Let a car merge in front of you without getting annoyed.",
  "Put back a shopping cart that is not yours.",
  "Offer directions to someone who looks lost.",
  "Ask a cashier how their shift is going, and listen.",
  "Pick up something a stranger dropped before they notice.",
  "Say good morning to the first three people you see.",
  "Let someone else take the parking spot you were waiting for.",
  "Give an honest compliment to someone serving you.",
  "Hold the elevator instead of pretending you did not see them.",
  "Let the person with fewer items go first.",
  "Tell a manager about an employee who did a good job.",
  "Give someone the last one of something.",
  "Offer your phone charger to a stranger who needs it.",
  "Make room without being asked.",
  "Thank a bus driver, barista, or cleaner today.",
  "Buy a coffee for the person working alone.",
  "Leave a five star review for a small business you like.",
  "Pick a stranger and quietly wish them well.",
  "Let someone finish their sentence before you speak.",
  "Give up the armrest.",
  "Say sorry first, even if you were not entirely wrong.",
  "Ask someone for a recommendation, then actually take it.",
  "Notice someone doing invisible work, and thank them.",
  "Give someone a genuine compliment about their work, not their looks.",
  "Let someone merge into your lane, your line, or your conversation.",
  "Ask the name of someone whose name you should already know.",
  "Wave to a neighbor you usually avoid eye contact with.",
  "Tell a stranger their dog, kid, or jacket is great.",
  "Carry something up the stairs for someone.",
  "Give someone the benefit of the doubt today.",
  "Stop and actually help when someone looks confused.",
  "Offer your spot to someone in a hurry.",
  "Be patient with the person who is slow today.",
];

export const RELATIONSHIPS = [
  "Send a text to someone you have not seen in a very long time.",
  "Call a family member just to ask how they are.",
  "Text a friend you have not spoken to in over a month.",
  "Reach out to someone who seemed down lately.",
  "Introduce two people who should know each other.",
  "Reply to the message you have been avoiding.",
  "Ask someone about their day and do not interrupt once.",
  "Tell a family member a specific memory you cherish.",
  "Send a photo that will make someone smile.",
  "Check in on a neighbor.",
  "Ask a friend what they are excited about right now.",
  "Apologize for something you have been putting off.",
  "Call the person you always mean to call.",
  "Ask someone how you can make their week easier.",
  "Tell a friend the thing you admire about them.",
  "Invite someone to something, even if they might say no.",
  "Sit with someone instead of texting them.",
  "Ask a grandparent or elder about their twenties.",
  "Forgive someone silently and let it go.",
  "Say yes to an invitation you would normally decline.",
  "Give someone your full attention for one whole conversation.",
  "Let someone else pick the plan today.",
  "Ask a friend what they are struggling with.",
  "Reconnect with someone who once helped your career.",
  "Tell someone you are proud of them.",
  "Write a short letter to someone who will not expect it.",
  "Cook or share a meal with someone.",
  "Ask a coworker something that is not about work.",
  "Send a voice note instead of a text.",
  "Thank a parent or guardian figure specifically.",
  "Remember something small someone told you, and ask about it.",
  "Make plans and actually put them on the calendar.",
  "Be the first to reach out this time.",
  "Tell someone how they changed your mind about something.",
  "Ask for help with something instead of doing it alone.",
  "Say thank you to someone important to you, out loud.",
  "Ask a sibling or cousin something you never asked.",
  "Tell someone the impact they had without knowing it.",
  "Send a message to someone who is having a hard year.",
  "Ask an old friend what they are up to now, and mean it.",
  "Take a friend up on the thing they keep offering.",
  "Be the one who remembers the birthday.",
  "Ask someone what they need instead of guessing.",
  "Tell a friend you miss them.",
  "Spend an hour with someone with nothing scheduled.",
];

export const GRATITUDE = [
  "Say thank you to someone who helped you years ago.",
  "Write down three things you are grateful for.",
  "Send a thank-you message to a teacher or mentor.",
  "Tell someone specifically why you appreciate them.",
  "Give credit publicly to someone who earned it.",
  "Thank someone who never gets thanked.",
  "Write down one thing today that went right.",
  "Name one thing your body did well for you today.",
  "Thank someone for a small thing they do every day.",
  "Tell a coworker their work made your job easier.",
  "Write down a person who shaped you, and why.",
  "Thank someone who told you a hard truth.",
  "Look around your room and name five things you are glad to have.",
  "Say thank you before you say anything else today.",
  "Tell someone what you learned from them.",
  "Appreciate something you normally complain about.",
  "Thank a friend for putting up with you.",
  "Write down one thing you took for granted this week.",
  "Tell someone their advice actually worked.",
  "Thank the person who introduced you to something you love.",
  "Notice one beautiful thing and stop for it.",
  "Say thank you to someone who cannot pay you back.",
  "Write down what you would miss most if it disappeared tomorrow.",
  "Thank someone for their patience with you.",
  "Give yourself credit for something you usually dismiss.",
  "Say thank you to people who helped you throughout your life.",
  "Thank someone who believed you before you believed yourself.",
  "Name one thing about today that you would not trade.",
  "Tell a former boss or colleague what they taught you.",
  "Thank the person who does the thing nobody notices.",
  "Recall a stranger who was kind to you once.",
  "Appreciate one thing about where you live.",
  "Tell someone their work mattered.",
  "Count what you have instead of what is missing.",
  "Thank someone for saying no to you.",
];

export const COMMUNITY_ENVIRONMENT = [
  "Pick up three pieces of litter you did not drop.",
  "Donate one item you have not used in a year.",
  "Support a small local business today.",
  "Leave your workspace cleaner than you found it.",
  "Bring your own bag, cup, or bottle everywhere today.",
  "Recycle something you would normally throw away.",
  "Give away something you no longer need.",
  "Eat one meal today with no meat.",
  "Walk, bike, or take transit instead of driving once.",
  "Take shorter showers today and notice the difference.",
  "Fix something instead of replacing it.",
  "Buy something secondhand instead of new.",
  "Turn off every light you are not using.",
  "Share a resource that helped you with someone who needs it.",
  "Put ten dollars toward a cause you believe in.",
  "Sign up for one thing you keep meaning to volunteer for.",
  "Leave a public space better than you found it.",
  "Learn the name of one plant or bird near your home.",
  "Give food you will not eat to someone who will.",
  "Use up something before you buy a replacement.",
  "Say something good about your neighborhood out loud.",
  "Water a plant that is not yours.",
  "Take the stairs every single time today.",
  "Combine your errands into one trip.",
  "Teach someone something you are good at, for free.",
  "Share a skill with a person who cannot pay for it.",
  "Vote, register, or read one thing about a local issue.",
  "Compost or save one thing from the trash today.",
  "Buy from someone who made the thing themselves.",
  "Give directions instead of pointing at a phone.",
  "Refill something instead of buying a new one.",
  "Donate blood, or find out where you could.",
  "Pick up litter on your street, not just in the park.",
  "Give a book away instead of shelving it again.",
  "Choose the option with less packaging today.",
  "Leave a seat, a spot, or a space for someone else.",
  "Learn one thing about a community near you.",
  "Repair a piece of clothing instead of tossing it.",
  "Share a meal with someone who eats alone.",
  "Do one thing that helps someone you will never meet.",
];

export const BODY_HEALTH = [
  "Drink only water today.",
  "Move your body for twenty minutes.",
  "Stretch for five minutes before bed.",
  "Go to bed thirty minutes earlier tonight.",
  "Wake up without hitting snooze.",
  "Eat one more serving of vegetables than usual.",
  "Take a ten minute walk with no phone.",
  "Do a five minute breathing exercise.",
  "Cook something you have never made before.",
  "Eat one meal without a screen.",
  "Get outside before noon.",
  "Do ten pushups, or ten of anything.",
  "Sit up straight every time you notice you are slouching.",
  "Put your phone away one hour before sleep.",
  "Take a walk somewhere you have never walked.",
  "Skip the thing you eat out of boredom.",
  "Stand up every hour today.",
  "Eat something you actually enjoy, slowly.",
  "Get fifteen minutes of sunlight.",
  "Do the workout you keep postponing.",
  "Drink a glass of water before your first coffee.",
  "Take the long way somewhere on purpose.",
  "Notice how you feel after eating today.",
  "Rest on purpose instead of collapsing.",
  "Do one thing today that makes tomorrow easier.",
  "Cook a meal from scratch instead of ordering.",
  "Walk somewhere you would normally drive.",
  "Stop eating when you are full, not when the plate is empty.",
  "Take the stairs, then take them again.",
  "Put on music and move for one whole song.",
  "Go a whole day without complaining about your body.",
  "Pack tomorrow's lunch tonight.",
  "Sleep with your phone outside the bedroom.",
  "Try a vegetable you have never cooked.",
  "Do a real warm up before you rush into the day.",
  "Notice your breathing three times today.",
  "Give yourself a full lunch break.",
];

export const MIND_LEARNING = [
  "Read ten pages of a book.",
  "Spend fifteen minutes learning something new.",
  "Listen to a full album without multitasking.",
  "Watch something that teaches you instead of numbs you.",
  "Learn five words in another language.",
  "Look up the answer to something you have wondered about.",
  "Spend twenty minutes on something creative.",
  "Reconnect with an old hobby for twenty minutes.",
  "Write one page about anything.",
  "Read something you expect to disagree with.",
  "Ask a question instead of giving advice today.",
  "Learn how something you use every day actually works.",
  "Teach yourself one keyboard shortcut and use it.",
  "Finish the thing you left at ninety percent.",
  "Take notes on something you want to remember.",
  "Explain something you know to someone who does not.",
  "Listen to a podcast about a field you know nothing about.",
  "Draw something badly and keep it.",
  "Practice the thing you are worst at for ten minutes.",
  "Read an article all the way to the end.",
  "Write down a question you cannot answer yet.",
  "Learn one fact about the place you live.",
  "Follow your curiosity for thirty uninterrupted minutes.",
  "Ask someone to explain their job to you.",
  "Rewrite something you wrote to make it shorter.",
  "Memorize something worth having in your head.",
  "Look up the origin of a word you use often.",
  "Study a map of somewhere you have never been.",
  "Learn the basics of a skill you have always envied.",
  "Read a poem twice.",
  "Find out how something in your home is made.",
  "Watch a documentary about something unfamiliar.",
  "Ask a better question than you asked yesterday.",
  "Learn one thing about the history of your street.",
  "Try to explain a hard idea in one sentence.",
  "Spend an hour making something with your hands.",
  "Look up a person you admire and read how they started.",
];

export const COURAGE_GROWTH = [
  "Do the hardest task on your list first.",
  "Say no to something that drains you.",
  "Ask for feedback from someone you trust.",
  "Have the conversation you have been avoiding.",
  "Ask for what you actually want.",
  "Admit you were wrong about something.",
  "Do one thing that scares you slightly.",
  "Send the message you drafted but never sent.",
  "Apply for the thing you feel underqualified for.",
  "Speak up in the meeting you usually stay quiet in.",
  "Ask a question you think is too basic to ask.",
  "Set a boundary and hold it today.",
  "Say the kind thing you were thinking but did not say.",
  "Try something you might be bad at.",
  "Cancel one thing that does not serve you.",
  "Tell the truth in a place you would normally soften it.",
  "Start the project you keep researching.",
  "Ask for a discount, a favor, or an extension.",
  "Introduce yourself to someone new.",
  "Share something you made before it is perfect.",
  "Change your mind out loud.",
  "Do the thing you said you would do last week.",
  "Sit with a hard feeling for five minutes instead of distracting yourself.",
  "Take the first step on something you have only planned.",
  "Let yourself be seen trying.",
  "Say the thing everyone is thinking but nobody has said.",
  "Ask someone to hold you to something.",
  "Volunteer for the thing you would normally avoid.",
  "Tell someone what you actually think, kindly.",
  "Go somewhere alone that you would normally avoid alone.",
  "Ask for the raise, the meeting, or the introduction.",
  "Quit something that is over.",
  "Say I do not know instead of guessing.",
  "Do the version of it that is scarier by ten percent.",
  "Follow up on the thing that went quiet.",
  "Put your name on something you made.",
  "Decide the thing you have been deciding for weeks.",
];

export const GENEROSITY = [
  "Do a chore that is not yours without mentioning it.",
  "Offer help before being asked.",
  "Do something kind without telling anyone.",
  "Give away something you were saving for no reason.",
  "Cover a small cost for someone quietly.",
  "Give your time to someone who needs it more than you do.",
  "Lend something without asking when you get it back.",
  "Make something for someone.",
  "Share credit for something you did.",
  "Give the better half away.",
  "Leave something useful for the next person.",
  "Pay a compliment behind someone's back.",
  "Help someone move, carry, or fix something.",
  "Give a real recommendation for someone who deserves it.",
  "Buy the thing your friend keeps saying they want.",
  "Send someone a resource without expecting a reply.",
  "Take on the annoying task nobody wants.",
  "Split the difference in someone else's favor.",
  "Give someone a head start.",
  "Do the dishes you did not dirty.",
  "Give away the thing someone admired at your place.",
  "Handle the thing your friend has been dreading.",
  "Send money to someone who needs it more, quietly.",
  "Let someone else have the win today.",
  "Say yes to a favor without weighing it first.",
  "Offer your seat, your time, or your turn.",
  "Cover for someone without making it a story.",
  "Give a stranger the thing you were about to throw away.",
  "Be generous with your attention today.",
  "Give without checking whether they noticed.",
];

export const REFLECTION = [
  "Write down one goal and the first small step toward it.",
  "Write down what is worrying you, then one thing you control.",
  "Write a short letter to your future self.",
  "Write down one thing you did well this week.",
  "Name the thing you are actually avoiding.",
  "Ask yourself what you would do if you were not afraid.",
  "Write down what a good day looks like for you.",
  "Notice one story you tell yourself that is not true.",
  "Sit quietly for ten minutes with no input.",
  "List what you want more of, and what you want less of.",
  "Ask yourself who you are trying to impress, and why.",
  "List three things you are carrying that are not yours.",
  "Plan one thing you are looking forward to.",
  "Give yourself the advice you would give a friend.",
  "Forgive yourself for one specific thing.",
  "Notice what you say yes to out of guilt.",
  "Say out loud the advice you need to hear.",
  "End the day by naming one win, however small.",
  "Ask what you would regret not doing this year.",
  "Choose one thing to let go of today.",
  "Picture your week and cut the one thing you dread most.",
  "Ask whether you are busy or actually productive.",
  "Name the person you are becoming this year.",
  "Consider what you would do with a completely free day.",
  "Identify the habit that costs you the most.",
  "Ask what you are pretending not to know.",
  "Decide what good enough looks like, then stop there.",
  "Look back at last year and name one thing that changed.",
];

export const ATTENTION_DIGITAL = [
  "Put your phone away during every meal today.",
  "Spend an hour with no screens at all.",
  "Delete an app that wastes your time.",
  "Turn off every notification you did not choose.",
  "Unfollow accounts that make you feel worse.",
  "Do one task without switching tabs.",
  "Leave your phone in another room for an hour.",
  "Check your phone only after you get out of bed.",
  "Reply properly instead of reacting with an emoji.",
  "Read the article before sharing it.",
  "Have a conversation with no phone on the table.",
  "Do one thing today at half your usual speed.",
  "Notice the first thing you reach for when you are bored.",
  "Take a photo of something beautiful you would normally pass.",
  "Look out a window for two minutes.",
  "Finish one thing before starting another.",
  "Silence your phone for the whole evening.",
  "Take a different route and notice something new.",
  "Do a task in silence, with no music or podcast.",
  "Put away one thing that has been sitting out for weeks.",
  "Tidy one small space and leave it better than you found it.",
  "Clean out one drawer, folder, or inbox.",
  "Fix one small thing that has been annoying you.",
  "Make your bed and notice how the room feels.",
  "Clear one thing off your list by just doing it now.",
  "Keep your phone face down for the whole day.",
  "Mute a group chat that drains you.",
  "Open one tab at a time for an hour.",
  "Answer email twice today instead of all day.",
  "Leave the house without headphones once.",
  "Watch one thing on purpose instead of whatever autoplays.",
];

// Interleaved so consecutive days rotate through themes rather than
// serving thirty kindness tasks in a row.
const GROUPS = [
  OUTWARD_STRANGERS,
  RELATIONSHIPS,
  BODY_HEALTH,
  GRATITUDE,
  MIND_LEARNING,
  COMMUNITY_ENVIRONMENT,
  COURAGE_GROWTH,
  ATTENTION_DIGITAL,
  GENEROSITY,
  REFLECTION,
];

function interleave(groups) {
  const out = [];
  const longest = Math.max(...groups.map((g) => g.length));
  for (let i = 0; i < longest; i++) {
    for (const group of groups) {
      if (i < group.length) {
        out.push(group[i]);
      }
    }
  }
  return out;
}

export const CHALLENGE_LIBRARY = interleave(GROUPS);

export const CATEGORIES = {
  OUTWARD_STRANGERS,
  RELATIONSHIPS,
  GRATITUDE,
  COMMUNITY_ENVIRONMENT,
  BODY_HEALTH,
  MIND_LEARNING,
  COURAGE_GROWTH,
  GENEROSITY,
  REFLECTION,
  ATTENTION_DIGITAL,
};
